In [50]:
#Ejercicio 1

In [51]:
import numpy as np
from sympy import Matrix, symbols, solve, Eq, N
from scipy.linalg import lu
from scipy.linalg import lu, lu_solve, lu_factor

In [52]:
def matrix_multiplication(A, B):
    """
    Esta función toma dos matrices A y B y devuelve su producto AB.
    """
    A = np.array(A)
    B = np.array(B)

    if A.shape[1] != B.shape[0]:
        raise ValueError("El número de columnas de A debe ser igual al número de filas de B")

    return np.dot(A, B)

In [53]:
A_a = [[2, -3], [3, -1]]
B_a = [[1, 5], [2, 0]]
C_a = matrix_multiplication(A_a, B_a)
print("Resultado de a:\n", C_a)

Resultado de a:
 [[-4 10]
 [ 1 15]]


In [54]:
A_b = [[2, -3], [3, -1]]
B_b = [[1, 5, -4], [-3, 2, 0]]
C_b = matrix_multiplication(A_b, B_b)
print("Resultado de b:\n", C_b)

Resultado de b:
 [[ 11   4  -8]
 [  6  13 -12]]


In [55]:
A_c = [[2, -3, 1], [4, 3, 0], [5, 2, -4]]
B_c = [[0, 1, -2], [1, 0, -1], [2, 3, -2]]
C_c = matrix_multiplication(A_c, B_c)
print("Resultado de c:\n", C_c)

Resultado de c:
 [[ -1   5  -3]
 [  3   4 -11]
 [ -6  -7  -4]]


In [56]:
A_d = [[2, 1, 2], [-2, 3, 0], [2, -1, 3]]
B_d = [[1, -2], [-4, 1], [0, 2]]
C_d = matrix_multiplication(A_d, B_d)
print("Resultado de d:\n", C_d)

Resultado de d:
 [[ -2   1]
 [-14   7]
 [  6   1]]


In [57]:
#Ejercicio 2

In [58]:
def is_invertible(matrix):
    """
    Esta función verifica si una matriz es invertible (no singular).
    """
    return np.linalg.det(matrix) != 0

def inverse_matrix(matrix):
    """
    Esta función devuelve la inversa de una matriz si es invertible.
    """
    if is_invertible(matrix):
        return np.linalg.inv(matrix)
    else:
        raise ValueError("La matriz no es invertible")

In [59]:
A_a = [[4, 2, 6], [3, 0, 7], [-2, -1, -3]]
A_b = [[1, 2, 0], [2, 1, -1], [3, 1, 1]]
A_c = [[1, 1, -1, 1], [1, 2, -4, -2], [2, 1, 1, 5], [-1, 0, -2, -4]]
A_d = [[4, 0, 0, 0], [6, 7, 0, 0], [9, 11, 0, 0], [5, 4, 1, 1]]

matrices = {"a": A_a, "b": A_b, "c": A_c, "d": A_d}
for name, matrix in matrices.items():
    try:
        if is_invertible(matrix):
            inv_matrix = inverse_matrix(matrix)
            print(f"La matriz {name} es no singular y su inversa es:\n{inv_matrix}\n")
        else:
            print(f"La matriz {name} es singular y no tiene inversa.\n")
    except ValueError as e:
        print(f"Error en la matriz {name}: {e}\n")

La matriz a es singular y no tiene inversa.

La matriz b es no singular y su inversa es:
[[-0.25   0.25   0.25 ]
 [ 0.625 -0.125 -0.125]
 [ 0.125 -0.625  0.375]]

La matriz c es singular y no tiene inversa.

La matriz d es singular y no tiene inversa.



In [60]:
#Ejercicio 3

In [61]:
def resolver_sistema(coeficientes, terminos_independientes):
    coeficientes = np.array(coeficientes)
    terminos_independientes = np.array(terminos_independientes)
    soluciones = np.linalg.solve(coeficientes, terminos_independientes)
    return soluciones

coeficientes = [
    [1, -1, 2, -1],
    [1, 0, -1, 1],
    [2, 1, 3, -4],
    [0, -1, 3, -4]
]

terminos_independientes_1 = [6, 4, -2, 5]
terminos_independientes_2 = [1, 1, 2, -1]
soluciones_1 = resolver_sistema(coeficientes, terminos_independientes_1)
soluciones_2 = resolver_sistema(coeficientes, terminos_independientes_2)
variables = ['x1', 'x2', 'x3', 'x4']

In [62]:
print("Soluciones para el primer sistema:")
for var, sol in zip(variables, soluciones_1):
    print(f"{var} = {sol}")

print("\nSoluciones para el segundo sistema:")
for var, sol in zip(variables, soluciones_2):
    print(f"{var} = {sol}")

Soluciones para el primer sistema:
x1 = 3.0
x2 = -6.5
x3 = -2.5
x4 = -1.5000000000000002

Soluciones para el segundo sistema:
x1 = 1.0
x2 = 0.5
x3 = 0.5
x4 = 0.5


In [63]:
#Ejercicio 4

In [64]:
def encontrar_alphas_singulares():
    alpha = symbols('alpha')
    A = Matrix([
        [1, -1, alpha],
        [2, 2, 1],
        [0, alpha, -3/2]
    ])

    det_A = A.det()
    print(f"Determinante de la matriz A: {det_A}")

    valores_alpha = solve(Eq(det_A, 0), alpha)
    
    valores_alpha = [N(val, 2) for val in valores_alpha]
    return valores_alpha

valores_alpha_singulares = encontrar_alphas_singulares()
print(f"Los valores de α que hacen que la matriz sea singular son: {valores_alpha_singulares}")

Determinante de la matriz A: 2*alpha**2 - alpha - 6.0
Los valores de α que hacen que la matriz sea singular son: [-1.5, 2.0]


In [65]:
#Ejercicio 5

In [66]:
def resolver_sistema_lineal(A, B, C):
    """
    Resuelve el sistema de ecuaciones lineales de la forma A(Bx) = C.

    Parámetros:
    - A: matriz de coeficientes (3x3)
    - B: matriz de coeficientes (3x3)
    - C: vector de constantes (3x1)

    Devuelve:
    - x: vector solución (3x1)
    """
    
    AB = np.dot(A, B)
    
    x = np.linalg.solve(AB, C)
    
    return x

A_a = np.array([[1, 0, 0], 
                [2, 1, 0], 
                [-1, 0, 1]])

B_a = np.array([[2, 3, -1], 
                [0, -2, 1], 
                [0, 0, 3]])

C_a = np.array([2, -1, 1])

A_b = np.array([[2, 0, 0], 
                [-1, 1, 0], 
                [3, 2, -1]])

B_b = np.array([[1, 1, 1], 
                [0, 1, 2], 
                [0, 0, 1]])

C_b = np.array([-1, 3, 0])

x_a = resolver_sistema_lineal(A_a, B_a, C_a)
x_b = resolver_sistema_lineal(A_b, B_b, C_b)

print("Solución del sistema (a):")
for i, val in enumerate(x_a, 1):
    print(f"x{i} = {val:.0f}")

print("\nSolución del sistema (b):")
for i, val in enumerate(x_b, 1):
    print(f"x{i} = {val:.0f}")


Solución del sistema (a):
x1 = -3
x2 = 3
x3 = 1

Solución del sistema (b):
x1 = 1
x2 = -5
x3 = 4


In [67]:
# Ejercicio 6

In [68]:
def lu_factorization(A):
    """
    Realiza la factorización LU de una matriz A.
    
    Parámetros:
    A (ndarray): Matriz cuadrada a factorizar.
    
    Retorna:
    P (ndarray): Matriz de permutación.
    L (ndarray): Matriz triangular inferior.
    U (ndarray): Matriz triangular superior.
    """
    P, L, U = lu(A)
    return P, L, U

A1 = np.array([[2, -1, 1],
               [3, 3, 9],
               [3, 3, 5]])

A2 = np.array([[1.012, -2.132, 3.104],
               [-2.132, 4.096, -7.013],
               [3.104, -7.013, 0.014]])

A3 = np.array([[2, 0, 0, 0],
               [1, 1.5, 0, 0],
               [0, -3, 0.5, 0],
               [2, -2, 1, 1]])

A4 = np.array([[2.1756, 4.0231, -2.1732, 5.1967],
               [-4.0231, 6.0000, 0, 1.1973],
               [-1.0000, -5.2107, 1.1111, 0],
               [6.0235, 7.0000, 0, -4.1561]])

P1, L1, U1 = lu_factorization(A1)
P2, L2, U2 = lu_factorization(A2)
P3, L3, U3 = lu_factorization(A3)
P4, L4, U4 = lu_factorization(A4)

print("Matriz A1:")
print("P1:\n", P1)
print("L1:\n", L1)
print("U1:\n", U1)

print("\nMatriz A2:")
print("P2:\n", P2)
print("L2:\n", L2)
print("U2:\n", U2)

print("\nMatriz A3:")
print("P3:\n", P3)
print("L3:\n", L3)
print("U3:\n", U3)

print("\nMatriz A4:")
print("P4:\n", P4)
print("L4:\n", L4)
print("U4:\n", U4)

Matriz A1:
P1:
 [[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]
L1:
 [[ 1.          0.          0.        ]
 [ 0.66666667  1.          0.        ]
 [ 1.         -0.          1.        ]]
U1:
 [[ 3.  3.  9.]
 [ 0. -3. -5.]
 [ 0.  0. -4.]]

Matriz A2:
P2:
 [[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
L2:
 [[ 1.          0.          0.        ]
 [-0.68685567  1.          0.        ]
 [ 0.32603093 -0.21424728  1.        ]]
U2:
 [[ 3.104      -7.013       0.014     ]
 [ 0.         -0.72091881 -7.00338402]
 [ 0.          0.          1.59897957]]

Matriz A3:
P3:
 [[1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
L3:
 [[ 1.          0.          0.          0.        ]
 [ 0.          1.          0.          0.        ]
 [ 1.          0.66666667  1.          0.        ]
 [ 0.5        -0.5         0.375       1.        ]]
U3:
 [[ 2.          0.          0.          0.        ]
 [ 0.         -3.          0.5         0.        ]
 [ 0.          0.          0.66666667  1.        ]
 [ 0.          0.          

In [69]:
# Ejercicio 7

In [70]:
def solve_using_lu(A, b):
    """
    Resuelve el sistema de ecuaciones Ax = b utilizando la factorización LU.
    
    Parámetros:
    A (ndarray): Matriz de coeficientes.
    b (ndarray): Vector de términos independientes.
    
    Retorna:
    x (ndarray): Solución del sistema de ecuaciones.
    """

    lu, piv = lu_factor(A)
    x = lu_solve((lu, piv), b)
    return x

A1 = np.array([[2, -1, 1],
               [3, 3, 9],
               [3, 3, 5]])

b1 = np.array([-1, 0, 4])

A2 = np.array([[1.012, -2.132, 3.104],
               [-2.132, 4.096, -7.013],
               [3.104, -7.013, 0.014]])

b2 = np.array([1.984, -5.049, -3.895])

A3 = np.array([[2, 0, 0, 0],
               [1, 1.5, 0, 0],
               [0, -3, 0.5, 0],
               [2, -2, 1, 1]])

b3 = np.array([3, 4.5, -6.6, 0.8])

A4 = np.array([[2.1756, 4.0231, -2.1732, 5.1967],
               [-4.0231, 6.0000, 0, 1.1973],
               [-1.0000, -5.2107, 1.1111, 0],
               [6.0235, 7.0000, 0, -4.1561]])

b4 = np.array([17.102, -6.1593, 3.0004, 0.0])

x1 = solve_using_lu(A1, b1)
x2 = solve_using_lu(A2, b2)
x3 = solve_using_lu(A3, b3)
x4 = solve_using_lu(A4, b4)

print("Solución para el sistema a:")
print("x1 =", x1)

print("\nSolución para el sistema b:")
print("x2 =", x2)

print("\nSolución para el sistema c:")
print("x3 =", x3)

print("\nSolución para el sistema d:")
print("x4 =", x4)


Solución para el sistema a:
x1 = [ 1.  2. -1.]

Solución para el sistema b:
x2 = [1. 1. 1.]

Solución para el sistema c:
x3 = [ 1.5  2.  -1.2  3. ]

Solución para el sistema d:
x4 = [2.9398512  0.0706777  5.67773512 4.37981223]
